from .login import login as login_bp
from .main import main as main_bp
from .user import user as user_bp
from .healthrecord import healthrecord as healthrecord_bp
from .patient import patient as patient_bp
from .registration import registration as registration_bp
from .invoice import invoice as invoice_bp
from .medication import medication as medication_bp
from .management import management as management_bp
